name = "EchelonForm"
uuid = "4fc3857a-21ba-4bcf-98bd-a5fd00b1a85c"
authors = ["ebelnikola <ebelnikola@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
